### ISSUE TITLE
Немодульная архитектура

### ISSUE THREAD

**Issue by ulmink** [unitpay/cscart-module#3]
Hi,

CS-Cart расширяется модулями, текущая реализация = модификация ядра:
1. это против стандартов кодирования под CS-Cart - https://www.cs-cart.ru/docs/latest/developer_guide/addons/
2. вашим пользователям надо делать sql-инъекцию, чтобы пользоваться оплатой, через модуль этого делать не надо
3. при обновлении версии CS-Cart легко потерять все, что не сделано модулями - студии-разработчики под CS-Cart отслеживают именно модули...

из текущей наработки сделать модуль очень просто:
1. надо создать файл app/addons/unitpay/addon.xml (рекомендую использовать версию 3.0 для XML - https://www.cs-cart.ru/docs/latest/developer_guide/addons/scheme/scheme3.0_structure.html ) и соответственно айди модуля **unitpay**
1.1. то, что сейчас лежит в install.sql перенести в тэг queries в addon.xml (инъекция будет делать автоматически при установке модуля)
2. перенести https://github.com/unitpay/cscart-module/tree/master/unitpay/app/payments в папку app/addons/unitpay/payments 
3. аналогичная операция для папки design
4. по файлу unitpay/callback.php придется переделать. Если я правильно понял, то Unitpay не поддерживает динамические URL для возврата в магазин и URL нужно жестко указывать в настройках личного кабинета. В любом случае callback.php нужно объединить с unitpay.php и в коробке есть похожий пример - app/payments/cardsave_hosted.php, т.е. ставится условие:
```
use Tygh\Registry;

if (!defined('BOOTSTRAP')) {
    if (!empty($_REQUEST[])) { // валидация ключевых входных параметров
        require Registry::get('config.dir.payments') . 'init_payment.php'; // подключение ядра для платежки

       // код колбэка
    }
}

// текущий код app/payments/unitpay.php, т.е. прием данных с кнопки оплатить и отправка данных в Unitpay

**Comment by 0TH0N** [comment]
Здравствуйте. Большое спасибо за ваш комментарий. Поработал по вашим замечаниям.

Есть один вопрос по пункту 4. Динамические URL для возврата в магазин есть, их надо в GET-параметрах указывать. В случае CMS обычно все "success" и "error" адресами указанными в ЛК Unitpay ограничивается. Но callback.php для другого нужен. Данный скрипт принимает от нас сообщения о статусе платежа: "в обработке", "успешен", "ошибка" и т.д.. И у этих сообщений определенный список GET-параметров https://help.unitpay.money/article/197-confirmation-payment . А в случае аддонов, как я понял, нужно отправлять дополнительно два параметра "mode" и "payment" https://docs.cs-cart.com/latest/developer_guide/addons/tutorials/payment_processor_addon.html для callback-скрипта, чего у нас нет, и целесообразности добавления этого ради одной CMS нет никакой.

Так что с "callback.php" я вижу только один путь пока, оставить как оно есть. Может вы что сможете подсказать?

**Comment by ulmink** [comment]
здравствуйте, @0TH0N 

коллеги подсказывают, что можно попробовать хитрость с route - [https://www.cs-cart.ru/docs/4.11.x/developer_guide/core/routing.html](https://www.cs-cart.ru/docs/4.11.x/developer_guide/core/routing.html)

конкретно в вашем случае необходимо:
4.1 создать схему `app/addons/unitpay/schemas/routes/objects.post.php` с примерным контентом:
```
<?php

defined('BOOTSTRAP') or die('Access denied');

$schema['/unitpay_callback'] = [
    'dispatch' => 'payment_notification.complete',
    'payment'  => 'unitpay',
];
```
4.2 в личном кабинете пользователям указывать www.site.com/unitpay_callback
4.3 далее объединить всю логику интеграции в `app/addons/unitpay/payments/unitpay.php`

надеюсь получится :+1:

**Comment by 0TH0N** [comment]
@ulmink выложили новую версию написанную согласно вашим рекомендациям. От лица компании позвольте выразить вам искреннюю благодарность за помощь и советы.

**Comment by ulmink** [comment]
@0TH0N был рад помочь
